# 使用轻量级Alpine镜像
image: alpine:latest

# 定义缓存策略（可选）
cache:
  paths:
    - public/

stages:
  - deploy

pages:
  stage: deploy
  script:
    # 安装必要工具
    - apk add --no-cache git bash
    # 创建发布目录
    - mkdir -p public
    # 复制所有文件到发布目录（排除.git等）
    - shopt -s extglob
    - cp -r !(.git*|.gitlab-ci.yml) public/
  artifacts:
    paths:
      - public
  only:
    - master