# .gitlab-ci.yml
pages:
  stage: deploy
  tags:
    - shell  # 匹配你的shell类型runner标签
  script:
    - mkdir -p public
    # 排除CI文件本身和.git目录
    - rsync ./src -a --exclude='.git/' --exclude='.gitlab-ci.yml' --exclude='public/' ./ public/
  artifacts:
    paths:
      - public
  only:
    - master  # 你的目标分支名称