# .gitlab-ci.yml
pages:
  stage: deploy
  tags:
    - shell  # 根据实际Runner环境调整（如使用docker则改为docker）
  script:
    # 创建发布目录（GitLab Pages强制要求必须用public）
    - mkdir -p public
    
    # 复制HTML、CSS和其他静态资源
    - cp index.html public/
    - cp -r css/ public/ || true
    - cp -r assets/ public/ || true
    
    # 复制webpack构建后的JS文件
    - cp -r dist/ public/
  artifacts:
    paths:
      - public
  only:
    - master  # 或改为你的主分支名称（如main）